# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "python setup.py sdist"
  - "mkdir tmp"
  - "ln ci/* tmp"
  - "cd tmp"
  - "pip install --upgrade pip"
  - "pip install $(echo ../dist/skyfield-*.tar.gz)'[tests]'"
  - "pip install https://github.com/brandon-rhodes/assay/archive/master.zip"
  - "pip install unittest2"
  - "curl -O ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de405.bsp"
  - "curl -O ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp"

script:
  - "assay --batch skyfield.tests"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]] ; then pip install astropy==3.0.1 numpy==1.14.2 sphinx==1.7.2 ; cd .. ; ln ci/* tmp/*.bsp skyfield/documentation ; ./test-docs.sh ; fi"
