# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# matrix:
#   include:
#     - python: "3.7"
#       dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
#       sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

install:
  - "python setup.py sdist"
  - "mkdir tmp"
  - "ln ci/* tmp"
  - "cd tmp"
  - "pip install --upgrade pip"
  - "pip install $(echo ../dist/skyfield-*.tar.gz)'[tests]'"
  - "pip install https://github.com/brandon-rhodes/assay/archive/master.zip"
  - "if [[ $TRAVIS_PYTHON_VERSION < 3.7 ]] ; then pip install numpy==1.11.3 scipy==1.2.2 pandas unittest2 ; else pip install pandas ; fi"
  - "python -c 'import pandas'"

script:
  - "../test-code.sh"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]] ; then pip install astropy==3.0.1 matplotlib==3.3.0 numpy==1.15.4 scipy==1.2.2 sphinx==1.7.2 spktype21 ; cd .. ; ./test-docs.sh ; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]] ; then pip install pyflakes ; pyflakes $(find skyfield/ -name '*.py') ; fi"
